import {
	Users,
	Settings,
	Award,
	Building,
	FileText,
	Calendar,
	Camera,
	Edit3,
	User,
	Mail,
} from 'lucide-react';

export const getDesignationColor = (designation) => {
	const colors = {
		CEO: 'bg-gradient-to-r from-purple-500 to-pink-500',
		CTO: 'bg-gradient-to-r from-blue-500 to-cyan-500',
		CFO: 'bg-gradient-to-r from-green-500 to-emerald-500',
		CMO: 'bg-gradient-to-r from-orange-500 to-red-500',
		COO: 'bg-gradient-to-r from-indigo-500 to-purple-500',
		Head: 'bg-gradient-to-r from-yellow-500 to-orange-500',
		member: 'bg-gradient-to-r from-slate-500 to-slate-600',
	};
	return colors[designation] || colors['member'];
};

export const getDepartmentIcon = (department) => {
	const icons = {
		HR: Users,
		Technical: Settings,
		Marketing: Award,
		Management: Building,
		'Content Writing': FileText,
		'Event Management': Calendar,
		Media: Camera,
		Design: Edit3,
		Coordinator: User,
		PR: Mail,
	};
	return icons[department] || User;
};

export const getStatusColor = (status) => {
	const colors = {
		active: 'text-green-700 bg-green-100 dark:bg-green-500/20 border border-green-200 dark:border-green-500/30',
		banned: 'text-red-700 bg-red-100 dark:bg-red-500/20 border border-red-200 dark:border-red-500/30',
		removed:
			'text-slate-700 bg-slate-100 dark:bg-slate-500/20 border border-slate-200 dark:border-slate-500/30',
	};
	return colors[status] || colors['active'];
};

// File validation utilities
export const validateFile = (file, type) => {
	const errors = [];

	if (!file) {
		errors.push('No file selected');
		return { isValid: false, errors };
	}

	if (type === 'image') {
		// Image validation
		const allowedTypes = ['image/jpeg', 'image/jpg', 'image/png', 'image/webp'];
		const maxSize = 5 * 1024 * 1024; // 5MB

		if (!allowedTypes.includes(file.type)) {
			errors.push('Please select a valid image file (JPEG, PNG, or WebP)');
		}

		if (file.size > maxSize) {
			errors.push('Image size must be less than 5MB');
		}
	} else if (type === 'document') {
		// Document validation
		const allowedTypes = [
			'application/pdf',
			'application/msword',
			'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
		];
		const maxSize = 10 * 1024 * 1024; // 10MB

		if (!allowedTypes.includes(file.type)) {
			errors.push('Please select a valid document (PDF, DOC, or DOCX)');
		}

		if (file.size > maxSize) {
			errors.push('Document size must be less than 10MB');
		}
	}

	return {
		isValid: errors.length === 0,
		errors,
	};
};

// Simulate upload progress for better UX
export const simulateProgress = (onProgress) => {
	let progress = 0;

	const interval = setInterval(() => {
		progress += Math.random() * 15 + 5; // Faster progress
		if (progress >= 95) {
			progress = 95;
			clearInterval(interval);
		}
		onProgress(Math.min(progress, 95));
	}, 150);

	return interval;
};

// Format file size
export const formatFileSize = (bytes) => {
	if (bytes === 0) return '0 Bytes';

	const k = 1024;
	const sizes = ['Bytes', 'KB', 'MB', 'GB'];
	const i = Math.floor(Math.log(bytes) / Math.log(k));

	return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
};

// Create thumbnail from file
export const createThumbnail = (file) => {
	return new Promise((resolve, reject) => {
		if (!file.type.startsWith('image/')) {
			reject(new Error('File is not an image'));
			return;
		}

		const reader = new FileReader();
		reader.onload = (e) => {
			const img = new Image();
			img.onload = () => {
				const canvas = document.createElement('canvas');
				const ctx = canvas.getContext('2d');

				// Set thumbnail size
				const maxSize = 200;
				const ratio = Math.min(maxSize / img.width, maxSize / img.height);
				canvas.width = img.width * ratio;
				canvas.height = img.height * ratio;

				// Draw thumbnail
				ctx.drawImage(img, 0, 0, canvas.width, canvas.height);

				canvas.toBlob(resolve, 'image/jpeg', 0.8);
			};
			img.src = e.target.result;
		};
		reader.onerror = reject;
		reader.readAsDataURL(file);
	});
};

// Skills to export for the members to select
export const allSkills = [
	'Full Stack Development',
	'MERN Stack',
	'Frontend Development',
	'Backend Development',
	'Data Structures',
	'Algorithms',
	'DSA',
	'UI/UX Design',
	'Graphic Design',
	'Content Writing',
	'Public Relations',
	'Event Management',
	'Marketing',
	'Social Media Management',
	'Photography',
	'Videography',
	'Editing (Photo/Video)',
	'Team Management',
	'Leadership',
	'Communication',
	'Problem Solving',
	'Project Coordination',
	'Finance Management',
	'Presentation Skills',
	'Research',
	'Copywriting',
	'Community Engagement',
	'Technical Support',
	'Cloud Computing',
	'App Development',
	'Data Analysis',
	'Networking',
	'Time Management',
	'Creativity',
	'Collaboration',
	'Critical Thinking',
	'Python Programming',
	'JavaScript',
	'Java',
	'C++',
	'C#',
	'React.js',
	'Node.js',
	'Express.js',
	'MongoDB',
	'SQL',
	'NoSQL',
	'API Development',
	'RESTful APIs',
	'Mobile App Development',
	'Android Development',
	'iOS Development',
	'Flutter',
	'React Native',
	'Testing & Debugging',
	'Unit Testing',
	'Automation',
	'Git & Version Control',
	'Agile Methodologies',
	'Scrum',
	'Kanban',
	'Documentation',
	'Public Speaking',
	'Negotiation',
	'Conflict Resolution',
	'Mentoring',
	'Teaching',
	'Workshop Facilitation',
	'Event Planning',
	'Budgeting',
	'Sponsorship Management',
	'Branding',
	'SEO',
	'SEM',
	'Email Marketing',
	'Analytics',
	'Google Analytics',
	'Figma',
	'Adobe Photoshop',
	'Adobe Illustrator',
	'Canva',
	'Video Production',
	'Sound Editing',
	'Podcasting',
	'Blogging',
	'Newsletter Creation',
	'Customer Support',
	'User Research',
	'Wireframing',
	'Prototyping',
	'Database Design',
	'System Administration',
	'Linux',
	'Windows Server',
	'Cybersecurity',
	'Penetration Testing',
	'Ethical Hacking',
	'Machine Learning',
	'Artificial Intelligence',
	'Data Visualization',
	'Spreadsheet Skills',
	'Publicity',
	'Fundraising',
	'Volunteer Coordination',
	'Resource Management',
	'Strategic Planning',
	'Risk Management',
	'Django',
	'Flask',
	'PHP',
	'Laravel',
	'Ruby on Rails',
	'Go',
	'TypeScript',
	'SASS/SCSS',
	'Bootstrap',
	'Tailwind CSS',
	'Material UI',
	'Redux',
	'Next.js',
	'Gatsby',
	'Jest',
	'Mocha',
	'Chai',
	'Cypress',
	'Selenium',
	'Jenkins',
	'Docker',
	'Kubernetes',
	'AWS',
	'Azure',
	'Google Cloud Platform',
	'Firebase',
	'Heroku',
	'Netlify',
	'Vercel',
	'Nginx',
	'Apache',
	'Shell Scripting',
	'PowerShell',
	'Arduino',
	'Raspberry Pi',
	'IoT',
	'Blockchain',
	'Solidity',
	'Smart Contracts',
	'UI Animation',
	'SVG Design',
	'Infographics',
	'Event Hosting',
	'Emceeing',
	'Voice Over',
	'Script Writing',
	'Storyboarding',
	'3D Modeling',
	'Blender',
	'Unity',
	'Unreal Engine',
	'Game Development',
	'Game Design',
	'Augmented Reality',
	'Virtual Reality',
	'Customer Relationship Management',
	'Sales',
	'Lead Generation',
	'Market Research',
	'Survey Design',
	'Data Entry',
	'Transcription',
	'Translation',
	'Multilingual Communication',
	'Sign Language',
	'Accessibility Design',
	'Sustainability Initiatives',
	'Green Technologies',
	'Peer Counseling',
	'Mental Health Advocacy',
	'Diversity & Inclusion',
	'Alumni Relations',
	'Club Promotion',
	'Poster Design',
	'Brochure Design',
	'Merchandise Design',
	'Logistics',
	'Inventory Management',
	'Procurement',
	'Legal Awareness',
	'Copyright Management',
	'Patent Research',
	'Grant Writing',
	'Proposal Writing',
	'Report Writing',
	'Minutes Taking',
	'Scheduling',
	'Task Management',
	'Roadmapping',
	'OKR Management',
	'KPI Tracking',
	'Quality Assurance',
	'Usability Testing',
	'A/B Testing',
	'Heatmap Analysis',
	'Customer Journey Mapping',
	'Persona Creation',
	'Onboarding',
	'Alumni Networking',
	'Peer Tutoring',
	'Hackathon Participation',
	'Competition Preparation',
	'Workshop Organization',
	'Seminar Coordination',
	'Panel Moderation',
	'Debate',
	'Quiz Mastering',
	'Cultural Event Management',
	'Sports Event Management',
	'Stage Management',
	'Lighting',
	'Sound Engineering',
	'Stage Decoration',
	'Props Management',
	'Ticketing',
	'Crowd Management',
	'Security Coordination',
	'First Aid',
	'Emergency Planning',
	'Sponsorship Outreach',
	'Vendor Management',
	'Catering Coordination',
	'Travel Arrangements',
	'Accommodation Management',
	'Feedback Collection',
	'Survey Analysis',
	'Data Cleaning',
	'Data Mining',
	'Big Data',
	'Cloud Security',
	'DevOps',
	'Continuous Integration',
	'Continuous Deployment',
	'Release Management',
	'Incident Response',
	'Disaster Recovery',
	'Backup Management',
	'Mobile UI Design',
	'Desktop App Development',
	'Electron.js',
	'Cross-platform Development',
	'Progressive Web Apps',
	'Browser Extensions',
	'API Documentation',
	'Open Source Contribution',
	'Community Moderation',
	'Forum Management',
	'Discord Management',
	'Slack Administration',
	'Telegram Bots',
	'Chatbot Development',
	'Natural Language Processing',
	'Computer Vision',
	'Robotics',
	'Embedded Systems',
	'PCB Design',
	'Circuit Simulation',
	'Matlab',
	'Simulink',
	'Statistical Analysis',
	'R Programming',
	'SPSS',
	'SAS',
	'Econometrics',
	'Financial Modeling',
	'Investment Analysis',
	'Entrepreneurship',
	'Business Development',
	'Pitching',
	'Incubation',
	'Startup Mentoring',
	'Patent Filing',
	'Intellectual Property',
	'Legal Compliance',
	'GDPR Awareness',
	'Ethics in Tech',
	'Sociocultural Awareness',
	'Event Photography',
	'Live Streaming',
	'OBS Studio',
	'YouTube Management',
	'Instagram Marketing',
	'Facebook Ads',
	'LinkedIn Outreach',
	'Twitter Engagement',
	'Snapchat Marketing',
	'Influencer Collaboration',
	'Brand Ambassador',
	'Ambassador Program Management',
	'Alumni Database Management',
	'Membership Drive',
	'Recruitment',
	'Interviewing',
	'Resume Screening',
	'Onboarding Process',
	'Exit Interviews',
	'Performance Review',
	'Recognition Programs',
	'Award Nomination',
	'Certificate Design',
	'Digital Badges',
	'Gamification',
	'Leaderboard Management',
	'Peer Review',
	'Surveys',
	'Focus Groups',
	'Case Study Analysis',
	'Whitepaper Writing',
	'Technical Blogging',
	'Vlogging',
	'Short Film Making',
	'Animation',
	'Stop Motion',
	'Motion Graphics',
	'After Effects',
	'Premiere Pro',
	'Final Cut Pro',
	'DaVinci Resolve',
	'Audio Mixing',
	'Music Production',
	'DJing',
	'Event Promotion',
	'Flyer Distribution',
	'Street Team Coordination',
	'Public Announcements',
	'Press Release Writing',
	'Media Outreach',
	'Journalism',
	'Interviewing Guests',
	'Panel Discussions',
	'Round Table Moderation',
	'Town Hall Organization',
	'Alumni Meetups',
	'Networking Events',
	'Career Counseling',
	'Resume Building',
	'LinkedIn Profile Optimization',
	'Mock Interviews',
	'Portfolio Development',
	'Personal Branding',
	'Self-Marketing',
	'Confidence Building',
	'Emotional Intelligence',
	'Stress Management',
	'Work-Life Balance',
	'Mindfulness',
	'Peer Support',
	'Conflict Mediation',
	'Team Bonding',
	'Icebreaker Activities',
	'Club Merchandise Sales',
	'E-commerce',
	'Online Store Management',
	'Payment Gateway Integration',
	'Order Fulfillment',
	'Customer Feedback',
	'Return Management',
	'Inventory Tracking',
	'Supply Chain Coordination',
	'Sustainability Reporting',
	'Green Event Planning',
	'Carbon Footprint Calculation',
	'Eco-friendly Initiatives',
	'Waste Management',
	'Recycling Programs',
	'Energy Conservation',
	'Water Conservation',
	'Environmental Awareness',
	'Social Impact Assessment',
	'CSR Initiatives',
	'Philanthropy',
	'Charity Drives',
	'Blood Donation Camps',
	'Health Camps',
	'Wellness Programs',
	'Yoga Sessions',
	'Meditation Workshops',
	'Fitness Challenges',
	'Sports Coaching',
	'Athlete Management',
	'Tournament Organization',
	'Scorekeeping',
	'Refereeing',
	'Umpiring',
	'Sports Analytics',
	'Player Scouting',
	'Talent Management',
	'Skill Assessment',
	'Learning & Development',
	'Online Course Creation',
	'MOOC Facilitation',
	'E-learning',
	'Webinar Hosting',
	'Virtual Event Management',
	'Hybrid Event Planning',
	'Digital Marketing',
	'Affiliate Marketing',
	'Growth Hacking',
	'Market Analysis',
	'Competitor Analysis',
	'SWOT Analysis',
	'PESTLE Analysis',
	'Business Strategy',
	'Vision Setting',
	'Mission Statement Drafting',
	'Goal Setting',
	'Milestone Tracking',
	'Retrospective Meetings',
	'Sprint Planning',
	'Daily Standups',
	'Retrospective Analysis',
	'Continuous Improvement',
	'Change Management',
	'Organizational Development',
	'Policy Drafting',
	'Constitution Writing',
	'Bylaws Management',
	'Election Management',
	'Voting System Design',
	'Ballot Counting',
	'Result Declaration',
	'Transparency Initiatives',
	'Accountability Programs',
	'Feedback Loops',
	'Suggestion Box Management',
	'Idea Incubation',
	'Innovation Management',
	'Patent Search',
	'Trademark Filing',
	'Copyright Registration',
	'Legal Documentation',
	'Contract Drafting',
	'MoU Preparation',
	'Agreement Review',
	'Risk Assessment',
	'Insurance Coordination',
	'Safety Protocols',
	'Fire Safety',
	'Evacuation Planning',
	'Emergency Drills',
	'First Responder Training',
	'Medical Aid',
	'Health & Safety Audits',
	'Compliance Checks',
	'Regulatory Reporting',
	'Audit Preparation',
	'Financial Auditing',
	'Tax Filing',
	'Budget Forecasting',
	'Expense Tracking',
	'Revenue Generation',
	'Profit Analysis',
	'Cost Optimization',
	'Resource Allocation',
	'Asset Management',
	'Inventory Auditing',
	'Procurement Planning',
	'Vendor Evaluation',
	'Supplier Relationship Management',
	'Contract Negotiation',
	'Purchase Order Management',
	'Invoice Processing',
	'Payment Reconciliation',
	'Banking Coordination',
	'Grant Management',
	'Scholarship Coordination',
	'Fellowship Management',
	'Mentorship Programs',
	'Alumni Mentoring',
	'Peer Learning',
	'Knowledge Sharing',
	'Best Practices Documentation',
	'Process Mapping',
	'Workflow Optimization',
	'Standard Operating Procedures',
	'Policy Implementation',
	'Change Communication',
	'Stakeholder Management',
	'Expectation Setting',
	'Conflict Avoidance',
	'Issue Resolution',
	'Escalation Management',
	'Root Cause Analysis',
	'Corrective Action Planning',
	'Preventive Action Planning',
	'Lessons Learned',
	'Knowledge Base Management',
	'Wiki Management',
	'Document Control',
	'Version Control',
	'Release Notes Writing',
	'Changelog Management',
	'User Manual Creation',
	'Helpdesk Management',
	'Ticketing System Administration',
	'Service Level Agreement Management',
	'Customer Satisfaction Surveys',
	'Net Promoter Score Tracking',
	'Customer Retention',
	'Loyalty Program Management',
	'Referral Program Management',
	'Ambassador Recruitment',
	'Brand Evangelism',
	'Community Building',
	'Online Community Engagement',
	'Forum Moderation',
	'Social Listening',
	'Sentiment Analysis',
	'Trend Analysis',
	'Influencer Marketing',
	'Content Strategy',
	'Editorial Calendar Management',
	'Content Scheduling',
	'Content Curation',
	'Content Distribution',
	'Content Repurposing',
	'Content Localization',
	'Multilingual Content Creation',
	'Translation Management',
	'Subtitling',
	'Captioning',
	'Accessibility Compliance',
	'WCAG Implementation',
	'Screen Reader Testing',
	'Alt Text Writing',
	'Color Contrast Testing',
	'Usability Audits',
	'User Testing',
	'Beta Testing',
	'Pilot Program Management',
	'Early Access Program Management',
	'Feedback Analysis',
	'Bug Tracking',
	'Issue Triage',
	'Patch Management',
	'Hotfix Deployment',
	'Release Planning',
	'Go-Live Coordination',
	'Post-Launch Support',
	'User Training',
	'Train-the-Trainer Programs',
	'Learning Path Design',
	'Certification Program Management',
	'Exam Proctoring',
	'Assessment Design',
	'Quiz Creation',
	'Survey Administration',
	'Poll Management',
	'Voting Platform Management',
	'Event Ticketing',
	'RSVP Management',
	'Attendance Tracking',
	'Check-in Management',
	'Badge Printing',
	'Lanyard Distribution',
	'Swag Bag Preparation',
	'Gift Distribution',
	'Prize Management',
	'Award Ceremony Planning',
	'Stage Setup',
	'Backdrop Design',
	'Lighting Design',
	'Sound Setup',
	'AV Coordination',
	'Live Translation',
	'Simultaneous Interpretation',
	'Signage Design',
	'Wayfinding',
	'Venue Decoration',
	'Theme Planning',
	'Table Arrangement',
	'Seating Chart Design',
	'VIP Coordination',
	'Guest List Management',
	'Invitation Design',
	'Invitation Distribution',
	'RSVP Follow-up',
	'Thank You Note Writing',
	'Post-Event Reporting',
	'Event Debrief',
	'Lessons Learned Documentation',
	'Continuous Feedback Collection',
	'Improvement Planning',
];
